# Generated by Django 2.1.5 on 2019-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='image_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
