# Generated by Django 2.1.5 on 2019-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotelroom_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='image_link',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
