# Generated by Django 2.1.5 on 2019-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190309_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='status',
            field=models.CharField(choices=[('bk', 'Booked'), ('pr', 'Processing')], default='bk', help_text='Status', max_length=2),
        ),
    ]
