# Generated by Django 2.1.5 on 2019-03-16 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190316_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular transaction', primary_key=True, serialize=False),
        ),
    ]
