# Generated by Django 2.1.5 on 2019-03-17 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_roomavailability_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailability',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
