# Generated by Django 2.1.7 on 2019-04-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(default='', max_length=500)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Hotel')),
            ],
        ),
    ]
