# Generated by Django 2.1.7 on 2019-04-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190331_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_seats',
            name='category',
            field=models.ForeignKey(default='Economy', on_delete=django.db.models.deletion.CASCADE, to='api.SeatType'),
        ),
    ]
