# Generated by Django 2.1.7 on 2019-04-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_hotelphotos'),
        ('api', '0017_auto_20190331_0821'),
    ]

    operations = [
    ]
