# Generated by Django 2.1.7 on 2019-04-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20190424_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat_availability',
            old_name='date',
            new_name='on_date',
        ),
    ]
