# Generated by Django 2.1.7 on 2019-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_operator_registered_hotel_registered_hotelphotos_registered_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
