# Generated by Django 2.1.7 on 2019-04-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190403_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_seats',
            name='category',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='api.SeatType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seattype',
            name='name',
            field=models.CharField(help_text='Enter type of seats', max_length=200, unique=True),
        ),
    ]
