# Generated by Django 2.1.7 on 2019-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190428_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
