# Generated by Django 2.1.7 on 2019-04-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190424_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_seats',
            name='price',
        ),
        migrations.AddField(
            model_name='flight_seats',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='flight_seats',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='seat_availability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
