# Generated by Django 2.1.7 on 2019-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_roomavailability_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_rooms',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='registered_rooms',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
