# Generated by Django 2.1.7 on 2019-04-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190429_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_seats',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='flight_seats',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='seat_availability',
            name='price',
        ),
    ]
