# Generated by Django 2.1.7 on 2019-04-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190403_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_seats',
            old_name='category',
            new_name='categoryseat',
        ),
        migrations.AlterField(
            model_name='seattype',
            name='name',
            field=models.CharField(help_text='Enter type of seats', max_length=200),
        ),
    ]
