# Generated by Django 2.1.7 on 2019-04-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190429_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_seats',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
