# Generated by Django 2.1.7 on 2019-04-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190403_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_seats',
            old_name='categoryseat',
            new_name='category',
        ),
    ]
