# Generated by Django 2.1.7 on 2019-04-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190429_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_seats',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='flight_seats',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seat_availability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
