# Generated by Django 2.1.7 on 2019-04-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190403_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat_availability',
            old_name='date',
            new_name='on_date',
        ),
    ]
