# Generated by Django 2.1.7 on 2019-04-17 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190417_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_seats',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular seat', primary_key=True, serialize=False),
        ),
    ]
